### ISSUE TITLE
Installation?

### ISSUE THREAD

**Issue by EpikGamer101** [ShadowlightStudios/shadowlight-engine#3]
How do you install this?

**Comment by ScaredStorm** [comment]
I think the best way to install the engine is to just clone (or fork then clone) the project.

There are also a couple of ways in using the engine. You can open the solution file and start making changes in ShadowlightEngine.cpp (because a main function is located here).
You can change the lump path to your own.

Another way of installing the engine is by importing the project in your own solution, after the import is done make sure to make it a static library and to remove the main function from ShadowlightEngine.cpp

**Comment by EpikGamer101** [comment]
How are you supposed to use the engine without downloading it though?

**Comment by EpikGamer101** [comment]
Also, if you have a position available, I would like to help with the development of this engine.

**Comment by ScaredStorm** [comment]
I am not a member of the dev team :) Just interested in this project. By the looks of things, the engine is now a standalone project. Clone the repository to your computer and start working in the ShadowlightEngine.h|cpp, or create your own entry point. You only have to change the location of the lump file.

But by the look of things shadowlight engine doesn't render (yet). So you'll have to implement that yourself.

**Comment by ShadowlightStudios** [comment]
Hey Epik, I can see you're new to GitHub. Basically, cloning is equivalent to downloading it. You're going to need Visual Studio with C++ to compile it, though, until I reach v1.0, where I'll include binaries.

**Comment by EpikGamer101** [comment]
Okay, thanks

I am immederite in Python, if you need the skills

On November 17, 2017, at 11:32 AM, ShadowlightStudios <notifications@github.com> wrote:

Hey Epik, I can see you're new to GitHub. Basically, cloning is equivalent to downloading it. You're going to need Visual Studio with C++ to compile it, though, until I reach v1.0, where I'll include binaries.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ShadowlightStudios/shadowlight-engine","title":"ShadowlightStudios/shadowlight-engine","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/ShadowlightStudios/shadowlight-engine">https://github.com/ShadowlightStudios/shadowlight-engine</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ShadowlightStudios in #3: Hey Epik, I can see you're new to GitHub. Basically, cloning is equivalent to downloading it. You're going to need Visual Studio with C++ to compile it, though, until I reach v1.0, where I'll include binaries."}],"action":{"name":"View Issue","url":"<a href="https://github.com/ShadowlightStudios/shadowlight-engine/issues/3#issuecomment-345293221">https://github.com/ShadowlightStudios/shadowlight-engine/issues/3#issuecomment-345293221</a>"}}}
