### ISSUE TITLE
Linking Errors with Unknown Cause

### ISSUE THREAD

**Issue by ShadowlightStudios** [ShadowlightStudios/shadowlight-engine#5]
I just pushed commit 949d4ec54ecd769f13d36722f379552002a63a34, which has a fatal compile-time bug involving the AssetArray class and the linker. For some reason, compiling the engine gives "unresolved externals" errors in the ShaderManager class, which so far is the only class that uses AssetArray. Here's my error log:
`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "public: __thiscall AssetArray<class Shader>::~AssetArray<class Shader>(void)" (??1?$AssetArray@VShader@@@@QAE@XZ) referenced in function __unwindfunclet$??0ShaderManager@@QAE@XZ$1	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall AssetArray<class Shader>::AssetArray<class Shader>(void)" (??0?$AssetArray@VShader@@@@QAE@XZ) referenced in function "public: __thiscall ShaderManager::ShaderManager(void)" (??0ShaderManager@@QAE@XZ)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall AssetArray<class Program>::~AssetArray<class Program>(void)" (??1?$AssetArray@VProgram@@@@QAE@XZ) referenced in function "public: virtual __thiscall ShaderManager::~ShaderManager(void)" (??1ShaderManager@@UAE@XZ)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: __thiscall AssetArray<class Program>::AssetArray<class Program>(void)" (??0?$AssetArray@VProgram@@@@QAE@XZ) referenced in function "public: __thiscall ShaderManager::ShaderManager(void)" (??0ShaderManager@@QAE@XZ)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall AssetArray<class Shader>::Gen<class VertexShader>(void)" (??$Gen@VVertexShader@@@?$AssetArray@VShader@@@@QAEHXZ) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall AssetArray<class Shader>::Gen<class GeometryShader>(void)" (??$Gen@VGeometryShader@@@?$AssetArray@VShader@@@@QAEHXZ) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall AssetArray<class Shader>::Gen<class FragmentShader>(void)" (??$Gen@VFragmentShader@@@?$AssetArray@VShader@@@@QAEHXZ) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: int __thiscall AssetArray<class Program>::Gen(void)" (?Gen@?$AssetArray@VProgram@@@@QAEHXZ) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: class Shader * __thiscall AssetArray<class Shader>::Get(int)" (?Get@?$AssetArray@VShader@@@@QAEPAVShader@@H@Z) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK2019	unresolved external symbol "public: class Program * __thiscall AssetArray<class Program>::Get(int)" (?Get@?$AssetArray@VProgram@@@@QAEPAVProgram@@H@Z) referenced in function "public: virtual int __thiscall ShaderManager::Create(class Lump const &)" (?Create@ShaderManager@@UAEHABVLump@@@Z)	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\ShadowlightEngine\ShaderManager.obj	1	
Error	LNK1120	10 unresolved externals	ShadowlightEngine	C:\Marcus\Dropbox\The_Way_Back\ShadowlightEngine\v1\ShadowlightEngine\Debug\ShadowlightEngine.exe	1	`

**Comment by ShadowlightStudios** [comment]
I turns out that templates are an exception regarding method location, they have to be in the header file. I moved all of AssetArray.cpp into AssetArray.h, and the problem was solved.

**Comment by EpikGamer101** [comment]
Good Job!

Sent from Mail for Windows 10

**Comment by EpikGamer101** [comment]
I can help if needed.

Sent from Mail for Windows 10
