### ISSUE TITLE
Shaders issue

### ISSUE THREAD

**Issue by EpikGamer101** [ShadowlightStudios/shadowlight-engine#6]
The shaders don't work..... 

also, can i apply for your team?

EDIT. the shaders work now...

**Comment by ShadowlightStudios** [comment]
Umm... I'm going to need a bit more details on what's your problem... and if you're interested, join the Discord server for Shadowlight Studios: https://discord.gg/VYUHEnB

**Comment by EpikGamer101** [comment]
I am already part of that discord…. The problem is fixed now


Sent from Mail for Windows 10
